### PR TITLE
Bugfix - fail on chunk's without 'src' property

### PR DESCRIPTION
**Pull request by RUVATA**

### CODE REVIEW

**Comment by RUVATA** [comment]
Resolves #3

**Comment by thearchitgarg** [comment]
Can you please change the base of your pull request. We now have [different branch] for 3.2.0 version (https://github.com/thearchitgarg/html-webpack-injector/tree/v3.2.0)

**Comment by thearchitgarg** [comment]
Thanks for the PR!!

**Comment by RUVATA** [comment]
> Thanks for the PR!!

Thanks for your solution :)

**Pull request merged**
